{% set data= load_setup_py_data() %}
package:
  name: dm-ocps
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_ocps = lsst.dm.OCPS.ocps_csc:run_ocps
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - DM_CONFIG_OCPS_DIR
    - LSST_DDS_PARTITION_PREFIX

test:
  requires:
    - ts-conda-build =0.3
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
  source_files:
    - bin
    - pyproject.toml
    - python
    - setup.cfg
    - tests
  commands:
    - py.test

requirements:
  host:
    - python {{ python }}
    - setuptools
    - setuptools_scm
  build:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - requests
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
